# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gXzCtuCu76qRF3Q8kvl4-eYavYZ3TZam
"""

import pandas as pd

data = pd.read_csv('bank_customer_data.csv')

print(data.head())
print(data.describe())

# Check for missing values
missing_values = data.isnull().sum()
print(missing_values)

# Example: Fill missing values with the median (for numerical columns)
data.fillna(data.median(), inplace=True)

# Drop rows with missing values (if appropriate)
# data.dropna(inplace=True)

import numpy as np
# Identifying outliers in 'Balance'
q1, q3 = np.percentile(data['Balance'], [25, 75])
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr)
upper_bound = q3 + (1.5 * iqr)

# Option to remove outliers
# data = data[(data['Balance'] >= lower_bound) & (data['Balance'] <= upper_bound)]

# Drop duplicate rows if they exist
data.drop_duplicates(inplace=True)

# Example: Standardize string format for 'Job' column
data['Job'] = data['Job'].str.lower()

# Exploratory Data Analysis

# 1. Age Distribution
plt.figure(figsize=(10, 6))
sns.histplot(data['Age'], bins=30, kde=True)
plt.title('Age Distribution of Bank Customers')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

# 2. Job Categories of Customers
plt.figure(figsize=(10, 6))
sns.countplot(y='Job', data=data)
plt.title('Job Categories of Customers')
plt.xlabel('Count')
plt.ylabel('Job')
plt.show()

# 3. Account Balance Distribution
plt.figure(figsize=(10, 6))
sns.boxplot(x=data['Balance'])
plt.title('Distribution of Account Balances')
plt.xlabel('Account Balance')
plt.show()

# 4. Marital Status Distribution
plt.figure(figsize=(10, 6))
sns.countplot(x='Marital_Status', data=data)
plt.title('Marital Status of Customers')
plt.xlabel('Marital Status')
plt.ylabel('Count')
plt.show()

# 5. Correlation Matrix
corr_matrix = data.corr()
plt.figure(figsize=(10, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix of Variables')
plt.show()

